[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "tg-gnn"
version = "0.1.0"
description = "Tigergraph GNN project"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [
    { name = "Zettabolt"}
]

keywords = ["graph", "gnn", "tigergraph"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]

# If you have direct dependencies, list them here:
dependencies = [
    "pyTigerGraph",
    "cugraph-cu12==25.6.*,>=0.0.0a0",
    "pylibwholegraph-cu12==25.6.*,>=0.0.0a0",
    "cugraph-pyg-cu12==25.6.*,>=0.0.0a0",
    "cudf-cu12==25.6.*,>=0.0.0a0",
    "numba>=0.57",
    "numpy>=1.23,<3.0a0",
    "pandas",
    "tensordict>=0.1.2",
    "torch-geometric>=2.5,<2.7",
    "torch>=2.3",
    "scikit-learn",
    "pytest",
    "ogb"

]

[project.optional-dependencies]
test = [
    "ogb",
    "pytest>=6.2.0",
    "scikit-learn"
]

[tool.setuptools.packages.find]
where = ["."]
